apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx0
  name: nginx0
  namespace: default
spec:
  ports:
  - nodePort: 30633
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}