apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp
  annotations:
    configmanagement.gke.io/cluster-selector: select-prod
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  