apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: acm-1b-stage
  git:
    syncRepo: git@github.com:benking84/acm.git
    syncBranch: stage
    secretType: ssh
    policyDir: "acme_corp"